name: keep_alive_builder
description: If need keep state, replace FutureBuilder or StreamBuilder with keep_alive_builder's components.
version: 1.0.0
homepage: https://leazer.top/

environment:
  sdk: '>=2.18.5 <3.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
